import { useState, useRef, useEffect } from "react";
import axios from "axios";
import { toast } from "sonner";
import ChatInput from "../components/ChatInput";
import ChatMessage from "../components/ChatMessage";
import FormulaCard from "../components/FormulaCard";
import { Terminal, Sparkles } from "lucide-react";
import { ScrollArea } from "../components/ui/scroll-area";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const ChatPage = () => {
  const [messages, setMessages] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId, setSessionId] = useState(null);
  const scrollRef = useRef(null);

  useEffect(() => {
    // Generate session ID on mount
    const newSessionId = crypto.randomUUID();
    setSessionId(newSessionId);
  }, []);

  useEffect(() => {
    // Scroll to bottom when new messages arrive
    if (scrollRef.current) {
      scrollRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages]);

  const handleSendMessage = async (message) => {
    if (!message.trim() || isLoading) return;

    // Add user message
    const userMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content: message,
      timestamp: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMessage]);
    setIsLoading(true);

    try {
      const response = await axios.post(`${API}/chat`, {
        message: message,
        session_id: sessionId,
      });

      const assistantMessage = {
        id: response.data.message_id,
        role: "assistant",
        content: response.data.user_text,
        user_text: response.data.user_text,
        technical: response.data.technical,
        timestamp: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, assistantMessage]);
      
      // Update session ID if it was generated by backend
      if (response.data.session_id) {
        setSessionId(response.data.session_id);
      }
    } catch (error) {
      console.error("Chat error:", error);
      toast.error("Failed to process command. Please try again.");
      
      // Add error message
      const errorMessage = {
        id: crypto.randomUUID(),
        role: "assistant",
        content: "Error processing your request. Please try again.",
        isError: true,
        timestamp: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div 
      data-testid="chat-page" 
      className="min-h-screen bg-[#09090b] relative overflow-hidden"
    >
      {/* Background texture */}
      <div 
        className="absolute inset-0 bg-texture opacity-5 mix-blend-overlay pointer-events-none"
        aria-hidden="true"
      />
      
      {/* Grid pattern */}
      <div 
        className="absolute inset-0 grid-pattern pointer-events-none"
        aria-hidden="true"
      />

      {/* Main content */}
      <div className="relative z-10 flex flex-col h-screen">
        {/* Header */}
        <header className="flex items-center gap-4 px-6 py-5 border-b border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
              <Terminal className="w-5 h-5 text-blue-400" />
            </div>
            <div>
              <h1 className="text-lg font-semibold tracking-tight text-white font-mono">
                Command Interpreter
              </h1>
              <p className="text-xs text-zinc-500">
                AI-powered formula generator
              </p>
            </div>
          </div>
          <div className="ml-auto flex items-center gap-2 text-xs text-zinc-500">
            <Sparkles className="w-3 h-3 text-blue-400" />
            <span>Powered by Claude</span>
          </div>
        </header>

        {/* Chat area */}
        <ScrollArea className="flex-1 px-4 md:px-8 lg:px-12">
          <div className="max-w-4xl mx-auto py-8 space-y-6">
            {messages.length === 0 ? (
              <div 
                data-testid="empty-state"
                className="flex flex-col items-center justify-center h-[60vh] text-center"
              >
                <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500/20 to-blue-600/10 border border-blue-500/20 flex items-center justify-center mb-6">
                  <Terminal className="w-8 h-8 text-blue-400" />
                </div>
                <h2 className="text-xl font-semibold text-white mb-2">
                  Start with a command
                </h2>
                <p className="text-zinc-500 max-w-md mb-8 leading-relaxed">
                  Type your request and I'll convert it into a hierarchical formula.
                  Try commands like "go to grids, create table, apply borders"
                </p>
                <div className="grid gap-3 text-left">
                  <ExamplePrompt 
                    text="Show grids"
                    onClick={() => handleSendMessage("Show grids")}
                  />
                  <ExamplePrompt 
                    text="Go to grids, create table, apply borders"
                    onClick={() => handleSendMessage("Go to grids, create table, apply borders")}
                  />
                  <ExamplePrompt 
                    text="Copy and paste"
                    onClick={() => handleSendMessage("Copy and paste")}
                  />
                </div>
              </div>
            ) : (
              messages.map((msg, index) => (
                <div key={msg.id} className="message-animate">
                  {msg.role === "user" ? (
                    <ChatMessage message={msg} />
                  ) : msg.user_text ? (
                    <FormulaCard 
                      userText={msg.user_text} 
                      technical={msg.technical} 
                      isError={msg.isError} 
                    />
                  ) : (
                    <ChatMessage message={msg} />
                  )}
                </div>
              ))
            )}
            
            {/* Loading indicator */}
            {isLoading && (
              <div className="flex items-center gap-2 px-6 py-4 glass rounded-2xl rounded-tl-sm max-w-[80%]">
                <div className="flex gap-1">
                  <div className="w-2 h-2 rounded-full bg-blue-400 typing-dot" />
                  <div className="w-2 h-2 rounded-full bg-blue-400 typing-dot" />
                  <div className="w-2 h-2 rounded-full bg-blue-400 typing-dot" />
                </div>
                <span className="text-sm text-zinc-400">Processing...</span>
              </div>
            )}
            
            <div ref={scrollRef} />
          </div>
        </ScrollArea>

        {/* Input area */}
        <div className="px-4 pb-8 pt-4">
          <div className="max-w-3xl mx-auto">
            <ChatInput 
              onSend={handleSendMessage} 
              disabled={isLoading}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

const ExamplePrompt = ({ text, onClick }) => (
  <button
    data-testid={`example-prompt-${text.toLowerCase().replace(/\s+/g, '-').slice(0, 20)}`}
    onClick={onClick}
    className="text-left px-4 py-3 rounded-lg bg-white/5 border border-white/10 text-sm text-zinc-400 hover:bg-white/10 hover:text-zinc-300 hover:border-blue-500/30 transition-all duration-200"
  >
    <span className="text-blue-400 mr-2">→</span>
    {text}
  </button>
);

export default ChatPage;
